// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCuTFMSQhlhWfTi8G-5m3ZBa_amZkRlXg',
    appId: '1:623742364391:web:94c5fa4cd0cce033939042',
    messagingSenderId: '623742364391',
    projectId: 'catatanai-final-project',
    authDomain: 'catatanai-final-project.firebaseapp.com',
    storageBucket: 'catatanai-final-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQ0obeOQ7tCSKEXCPrR56F36KU1wwLPk',
    appId: '1:623742364391:android:289873ca5c9c5583939042',
    messagingSenderId: '623742364391',
    projectId: 'catatanai-final-project',
    storageBucket: 'catatanai-final-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGYPA5rtve4Cc5-hog1519rM7Nc0dt6o',
    appId: '1:623742364391:ios:c120a2b34903e7f7939042',
    messagingSenderId: '623742364391',
    projectId: 'catatanai-final-project',
    storageBucket: 'catatanai-final-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectSanbercode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGYPA5rtve4Cc5-hog1519rM7Nc0dt6o',
    appId: '1:623742364391:ios:c120a2b34903e7f7939042',
    messagingSenderId: '623742364391',
    projectId: 'catatanai-final-project',
    storageBucket: 'catatanai-final-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectSanbercode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCuTFMSQhlhWfTi8G-5m3ZBa_amZkRlXg',
    appId: '1:623742364391:web:e720dbbc0503137a939042',
    messagingSenderId: '623742364391',
    projectId: 'catatanai-final-project',
    authDomain: 'catatanai-final-project.firebaseapp.com',
    storageBucket: 'catatanai-final-project.firebasestorage.app',
  );
}
